<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
namespace OC\Files\Cache;

use OCP\DB\QueryBuilder\IQueryBuilder;
use OCP\IDBConnection;

/**
 * Handle the mapping between the string and numeric storage ids
 *
 * Each storage has 2 different ids
 *    a string id which is generated by the storage backend and reflects the configuration of the storage (e.g. 'smb://user@host/share')
 *    and a numeric storage id which is referenced in the file cache
 *
 * A mapping between the two storage ids is stored in the database and accessible through this class
 *
 * @package OC\Files\Cache
 * @psalm-api
 */
class StorageGlobal {
	/** @var array<string, array{id: string, numeric_id: int, available: bool, last_checked: int}> */
	private array $cache = [];

	/** @var string[] */
	private $idByNumericIdCache = [];

	public function __construct(
		private readonly IDBConnection $connection,
	) {
	}

	static private function selectStorageInfo($builder)
	{
		return $builder->select(['id', 'numeric_id', 'available', 'last_checked', 'fileid'])
			->from('storages', 'storages')
			->leftJoin(
				'storages', 'filecache', 'fc',
				$builder->expr()->andX(
					$builder->expr()->eq('storages.numeric_id', 'fc.storage'),
					$builder->expr()->eq('fc.path', $builder->createNamedParameter(''))
				));
	}

	/**
	 * @param string[] $storageIds
	 */
	public function loadForStorageIds(array $storageIds) {

		$storageIds = array_values(array_map([Storage::class, 'adjustStorageId'], $storageIds));

		$builder = $this->connection->getQueryBuilder();
		$query = self::selectStorageInfo($builder);
		$query->where($builder->expr()->in('id', $builder->createParameter('ids'), IQueryBuilder::PARAM_STR_ARRAY));
		foreach (array_chunk($storageIds, 1000) as $chunk) {
			$query->setParameter('ids', $chunk, IQueryBuilder::PARAM_STR_ARRAY);

			$result = $query->executeQuery();
			while ($row = $result->fetch()) {
				$normalizedRow = [
					'id' => (string)$row['id'],
					'numeric_id' => (int)$row['numeric_id'],
					'available' => (bool)$row['available'],
					'last_checked' => (int)$row['last_checked'],
					'fileid' => (int)$row['fileid'],
				];
				$this->cache[$normalizedRow['id']] = $normalizedRow;
				$this->idByNumericIdCache[$normalizedRow['numeric_id']] = $normalizedRow['id'];
			}
			$result->closeCursor();
		}
	}

	/**
	 * @param string[] $numericIds
	 */
	public function loadForNumericIds(array $numericIds) {
		$builder = $this->connection->getQueryBuilder();
		$query = self::selectStorageInfo($builder);
		$query->where($builder->expr()->in('numeric_id', $builder->createParameter('ids'), IQueryBuilder::PARAM_STR_ARRAY));
		foreach (array_chunk($numericIds, 1000) as $chunk) {
			$query->setParameter('ids', $chunk, IQueryBuilder::PARAM_STR_ARRAY);

			$result = $query->executeQuery();
			while ($row = $result->fetch()) {
				$normalizedRow = [
					'id' => (string)$row['id'],
					'numeric_id' => (int)$row['numeric_id'],
					'available' => (bool)$row['available'],
					'last_checked' => (int)$row['last_checked'],
					'fileid' => (int)$row['fileid'],
				];
				$this->cache[$normalizedRow['id']] = $normalizedRow;
				$this->idByNumericIdCache[$normalizedRow['numeric_id']] = $normalizedRow['id'];
			}
			$result->closeCursor();
		}
	}

	/**
	 * @return array{id: string, numeric_id: int, available: bool, last_checked: int}|null
	 */
	public function getStorageInfo(string $storageId): ?array {
		$storageId = Storage::adjustStorageId($storageId);
		if (!isset($this->cache[$storageId])) {
			$this->loadForStorageIds([$storageId]);
		}

		return $this->cache[$storageId] ?? null;
	}

	/**
	 * @return array{id: string, numeric_id: int, available: bool, last_checked: int}|null
	 */
	public function getStorageInfoByNumericId(int $numericId): ?array {
		if (!isset($this->numericIdCache[$numericId])) {
			$this->loadForNumericIds([$numericId]);
		}

		return $this->numericIdCache[$numericId] ?? null;
	}

	/**
	 * Get the string id for the storage
	 *
	 * @param int $numericId
	 * @return string|null either the storage id string or null if the numeric id is not known
	 */
	public function getStorageId($numericId)
	{
		if (!isset($this->idByNumericIdCache[$numericId])) {
			$this->loadForNumericIds([$numericId]);
		}
		return $this->idByNumericIdCache[$numericId] ?? null;
	}

	public function clearCache(): void {
		$this->cache = [];
		$this->idByNumericIdCache = [];
	}
}
